spring:
  application:
    name: reminder
  datasource:
    url: jdbc:postgresql://localhost:5432/reminder
    username: postgres
    password: 2212
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
        hibernate:
          format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  servlet:
    context-path: /api/v1
